version: 2

jobs:
  build:
    working_directory: ~/spookystuff-ci # change to something irregular
    docker:
      - image: maven:latest

        environment:
#          SITL_SPEEDUP: 10
#          SITL_RATE: 200
    steps:
      - checkout

      - run: 'exec build-tools/mvn-install.sh -Puav'

      - run: 'mvn test -Puav -pl uav'

# for 2.0 beta.